version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes: 
      - ./data:/data/db
    ports:
      - "27017:27017" 
# Image commented to stay a exmepla of run
  # api:
  #   container_name: api-container
  #   build: .
  #   image: clean-api
  #   restart: always
  #   command: bash -c "npm install --only=prod && npm run start"
  #   volumes:
  #     - ./dist:/usr/src/clean-api/dist
  #   ports:
  #     - "5050:5050"
  #   environment:
  #     - MONGO_URL=mongodb://mongo:27017/clean-node-api
  #   links:
  #    - mongo
